/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eteka
 */
public class userInterface extends javax.swing.JFrame {

    /**
     * Creates new form userInterface
     */
    public userInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previous = new javax.swing.JButton();
        afichprevious = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        afichnext = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        recherch = new javax.swing.JTextField();
        chercher = new javax.swing.JButton();
        rechercherTout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("of");

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel2.setText("Adress ID :");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel3.setText("First Name :");

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name :");

        jLabel5.setText("Email :");

        jLabel6.setText("Phone Number :");

        insert.setText("Insert New Entry");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        chercher.setText("Find");
        chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherActionPerformed(evt);
            }
        });

        rechercherTout.setText("Browse all entries");
        rechercherTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherToutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(afichprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(afichnext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prenom)
                                    .addComponent(id)
                                    .addComponent(nom)
                                    .addComponent(email)
                                    .addComponent(phone)
                                    .addComponent(recherch, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(chercher, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38)
                                .addComponent(rechercherTout)))))
                .addContainerGap(521, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afichprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(afichnext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recherch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chercher))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(rechercherTout))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed

        contact cont = new contact(id.getText() , prenom.getText() ,nom.getText() , email.getText() , phone.getText());
        
        cont.inserer();
        
       javax.swing.JOptionPane.showMessageDialog(null,"insertion reussi"); 
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_insertActionPerformed

    
     public void rechercher(String nam){
    
     try {
              String url = "jdbc:mysql://localhost:3306/examenjava?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC";
            String user = "root";
            String pw = "";
            
            String req = "select * from contacte  where nom ='";
            req += nam;
            req+="';";
            
            Connection con = DriverManager.getConnection(url,user,pw);
            Statement stat = con.createStatement();
            
            ResultSet result = stat.executeQuery(req);
            
            ResultSetMetaData resultMeta = result.getMetaData();
            
          while(result.next()){
              
              nom.setText(result.getString("nom"));
              
              prenom.setText(result.getString("prenom"));
              
              id.setText(result.getString("adress_id"));
              
              email.setText(result.getString("email"));
              
              phone.setText(result.getString("numero"));
              
            
            }
            
       
            
// TODO code application logic here
        } catch (SQLException ex) {
             javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
            
    }  
    
    
    private void chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherActionPerformed
   rechercher(recherch.getText());
      // TODO add your handling code here:
    }//GEN-LAST:event_chercherActionPerformed

    
    public void browser(){
    
        
        int cnt = 0 ; 
          try {
              String url = "jdbc:mysql://localhost:3306/examenjava?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC";
            String user = "root";
            String pw = "";
            
            String req = "select * from contacte ";
            
            
            Connection con = DriverManager.getConnection(url,user,pw);
            Statement stat = con.createStatement();
            
            ResultSet result = stat.executeQuery(req);
            
            ResultSetMetaData resultMeta = result.getMetaData();
            
          while(result.next()){
              
            
              cnt ++;
            
            }
          
        afichprevious.setText("1");
            afichnext.setText(String.valueOf(cnt));
            
            
            
      
            
// TODO code application logic here
        } catch (SQLException ex) {
             javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
            
         
          
          
          first();
          
    
    }
    
    
    public void first(){
    
       int iden = 1;
       String idn = String.valueOf(iden);
         try {
              String url = "jdbc:mysql://localhost:3306/examenjava?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC";
            String user = "root";
            String pw = "";
            
            String req = "select * from contacte  where id ='";
            req += idn;
            req+="';";
            
            Connection con = DriverManager.getConnection(url,user,pw);
            Statement stat = con.createStatement();
            
            ResultSet result = stat.executeQuery(req);
            
            ResultSetMetaData resultMeta = result.getMetaData();
            
          while(result.next()){
              
              nom.setText(result.getString("nom"));
              
              prenom.setText(result.getString("prenom"));
              
              id.setText(result.getString("adress_id"));
              
              email.setText(result.getString("email"));
              
              phone.setText(result.getString("numero"));
              
            
            }
            
       
            
// TODO code application logic here
        } catch (SQLException ex) {
             javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }
    
    
    private void rechercherToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherToutActionPerformed

browser();
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercherToutActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
  
  
  
  
  int val = Integer.valueOf(afichprevious.getText());
  
  int calcul = val - 1 ;
  
  afichprevious.setText(String.valueOf(calcul));
  
   try {
              String url = "jdbc:mysql://localhost:3306/examenjava?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC";
            String user = "root";
            String pw = "";
            
            String req = "select * from contacte  where id ='";
            req += calcul;
            req+="';";
            
            Connection con = DriverManager.getConnection(url,user,pw);
            Statement stat = con.createStatement();
            
            ResultSet result = stat.executeQuery(req);
            
            ResultSetMetaData resultMeta = result.getMetaData();
            
          while(result.next()){
              
              nom.setText(result.getString("nom"));
              
              prenom.setText(result.getString("prenom"));
              
              id.setText(result.getString("adress_id"));
              
              email.setText(result.getString("email"));
              
              phone.setText(result.getString("numero"));
              
            
            }
            
       
            
// TODO code application logic here
        } catch (SQLException ex) {
             javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
  
  
// TODO add your handling code here:
    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

int val = Integer.valueOf(afichprevious.getText());

int calcul = val + 1 ;

afichprevious.setText(String.valueOf(calcul));

  
   try {
              String url = "jdbc:mysql://localhost:3306/examenjava?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC";
            String user = "root";
            String pw = "";
            
            String req = "select * from contacte  where id ='";
            req += calcul;
            req+="';";
            
            Connection con = DriverManager.getConnection(url,user,pw);
            Statement stat = con.createStatement();
            
            ResultSet result = stat.executeQuery(req);
            
            ResultSetMetaData resultMeta = result.getMetaData();
            
          while(result.next()){
              
              nom.setText(result.getString("nom"));
              
              prenom.setText(result.getString("prenom"));
              
              id.setText(result.getString("adress_id"));
              
              email.setText(result.getString("email"));
              
              phone.setText(result.getString("numero"));
              
            
            }
            
       
            
// TODO code application logic here
        } catch (SQLException ex) {
             javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField afichnext;
    private javax.swing.JTextField afichprevious;
    private javax.swing.JButton chercher;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton next;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton previous;
    private javax.swing.JTextField recherch;
    private javax.swing.JButton rechercherTout;
    // End of variables declaration//GEN-END:variables
}
